---
- name: "Make timezone London"
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/London
    dest: /etc/localtime
    state: link
    force: true
  become: true
  become_method: sudo
  register: tzconfig

- name: "Reset timezone"
  shell: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
  become: true
  become_method: sudo
  when: tzconfig.changed

- name: "Mount shared folders on boot."
  ansible.builtin.cron:
    name: "Mount shared folders on boot."
    special_time: reboot
    job: "/usr/local/bin/mount-shared-folders"

- name: "Add kali user to kali-trusted group to give them sudo nopasswd"
  ansible.builtin.user:
    name: kali
    groups: kali-trusted
    append: yes
  become: true
  become_method: sudo

- name: "Reset keyboard"
  shell: |
    echo "debconf keyboard-configuration/layout select English (UK)" | debconf-set-selections
    echo "debconf keyboard-configuration/layoutcode  string gb" | debconf-set-selections
  become: true
  become_method: sudo
